apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: loadtest
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: loadtest
  minReplicas: 4
  maxReplicas: 10
  metrics:
  - type: Object
    object:
      metric:
        name: requests-per-second
      describedObject:
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        name: ingress-homeserver
      target:
        type: Value
        value: "20"        
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 20
      policies:
      - type: Percent
        value: 10
        periodSeconds: 30
      selectPolicy: Min
