apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: single-default-backend-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/secure-backends: "true"
spec:
  tls:
  - hosts:
    - nganfamily.com
    secretName: letsencrypt-staging
  rules:
    - host: nganfamily.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginxhello
                port:
                  number: 80
