apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: single-default-backend-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  # tls:
  # - hosts:
  #   - nganfamily.com
  #   secretName: tls-secret
  rules:
    - host: nganfamily.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginxhello
                port:
                  number: 80
