apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    app: helloworld
  name: single-default-backend-ingress
  annotations:
    fluxcd.io/ignore: "false"
spec:
  backend:
    serviceName: helloworld
    servicePort: 80

